application:
  jdbc:
    driver: "org.h2.Driver"
    url: "jdbc:h2:mem:altoEditorTestDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    username: "altoEditor"
    password: "replaceMe"
  store:
    path: "/tmp/altoEditorTestStore"
    pattern: "xx/xx/xx"
  kramerius-instances:
    k7-mzk:
      title: "Kramerius 7 - MZK"
      url: "https://api.kramerius.mzk.cz/"
      serviceClientId: "replaceMe"
      serviceSecret: "replaceMe"
  engines:
    pero:
      exec: "python"
      entry: "/usr/local/bin/pero.py"

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        search:
          backend:
            directory:
              root: /tmp/hibernate-search-index

logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql.BasicBinder: off
    org.hibernate.orm.jdbc.bind: off
    org.hibernate: warn